
spring.application.name=cibertec
server.port=8081
jwt.secret=MiClaveSuperSeguraParaJWT2026HotelProyectoFinalCibertecSistemasSecurityKey
jwt.expiration=86400000
spring.datasource.url=jdbc:postgresql://localhost:5432/DB_HOTEL
spring.datasource.username=postgres
spring.datasource.password=p12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#rutas de pruebas
spring.thymeleaf.check-template-location=false
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG